- hosts: all
  become: yes
  gather_facts: False

  pre_tasks:

    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""

    - name: Gather facts now
      setup: # aka gather_facts

  tasks:

    - name: Install packages
      apt:
        name: "{{ item }}"
      with_items:
        - nginx
        - ruby-rails

    - name: Create basic ruby on rails app
      script: create_rails_app.sh
      become_user: ubuntu
      changed_when: False

    - name: Configure default virtual host
      copy:
        src: default
        dest: /etc/nginx/sites-available/
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
