- name: Configure common nameserver stuff
  hosts: all
  become: yes
  roles:
    - common

- name: Configure primary nameserver
  hosts: primary
  become: yes
  roles:
    - primary

- name: Configure slave nameserver
  hosts: slave
  become: yes
  roles:
    - slave

- name: Update record on primary
  hosts: primary
  become: yes
  roles:
    - nsupdate
