# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :primary do |primary_config|
      primary_config.vm.box = "centos/7"
      primary_config.vm.hostname = "primary"
      primary_config.vm.network :private_network, ip: "10.0.15.11"
      primary_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
      primary_config.vm.provision :shell, path: "bootstrap-primary.sh"
  end

  config.vm.define :slave do |slave_config|
      slave_config.vm.box = "centos/7"
      slave_config.vm.hostname = "slave"
      slave_config.vm.network :private_network, ip: "10.0.15.12"
      slave_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
      slave_config.vm.provision :shell, path: "bootstrap-slave.sh"
  end

end
