- name: Configure bind
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest}}"
  with_items:
    - { src: "named.conf.j2", dest: "/etc/named.conf" }
  notify:
    - restart bind

- name: Enable and start bind
  service:
    name: named
    enabled: yes
    state: started
